
#
# Makefile for SOC SAL support (VxWorks/Tornado)
#
LOCALDIR = src/sal/core/unix

include ${SDK}/make/Make.config

lib = libsal_core_plat
include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
