
#
# Makefile for SOC SAL support
#
LOCALDIR = lib/unixlib/netl

include ${SDK}/mk/Make.config
CFLAGS+=-I${SDK}/lib/unixlib/quagga

lib = libnetl
include ${SDK}/mk/Make.lib

include ${SDK}/mk/Make.depend
