
#
# Makefile for SOC SAL support
#

LOCALDIR = src/sal/appl

include ${SDK}/make/Make.config

subdirs=${targetbase} editline

include ${SDK}/make/Make.subdirs


lib = libsal_appl

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend



