
#
# Makefile for SOC SAL support (Linux Kernel)
#
LOCALDIR = src/sal/core/linux

include ${SDK}/make/Make.config

lib = libsal_core_plat
include ${SDK}/make/Make.kernlib

include ${SDK}/make/Make.depend
