
#
# Makefile for SOC SAL support (Linux Kernel)
#
LOCALDIR = lib/sal/core/linuxkern

include ${SDK}/mk/Make.config

lib = libsal_core_plat
include ${SDK}/mk/Make.kernlib

include ${SDK}/mk/Make.depend
