
#
# Makefile for SOC SAL support
#
LOCALDIR = lib/sal/core

include ${SDK}/mk/Make.config

subdirs=${targetbase}
include ${SDK}/mk/Make.subdirs

lib = libsal_core
include ${SDK}/mk/Make.kernlib

include ${SDK}/mk/Make.depend
