
#
# Makefile for StrataXGS SDK and diagnostics
#

include $(SDK)/mk/Make.config

ifeq ($(HOSTTYPE),i386-linux)
subdirs= xxx diag 
endif

include $(SDK)/mk/Make.subdirs

include $(SDK)/mk/Make.depend
