
#
# Makefile for SOC SAL support
#
LOCALDIR = lib/unixlib/halu

include ${SDK}/mk/Make.config
CFLAGS+=-I${SDK}/lib/unixlib/quagga

lib = libhalu
include ${SDK}/mk/Make.lib

include ${SDK}/mk/Make.depend
