
#
# Makefile for SOC SAL support
#
LOCALDIR = systems/linux/kernel/modules

include ${SDK}/mk/Make.config

subdirs= uk-proxy  bcm-core 

include ${SDK}/mk/Make.subdirs

include ${SDK}/mk/Make.depend
