
#
# Makefile for SOC SAL support
#
LOCALDIR = systems/linux/kernel/modules

include ${SDK}/make/Make.config

subdirs= uk-proxy  bcm-core 

include ${SDK}/make/Make.subdirs

include ${SDK}/make/Make.depend
