
#
# Makefile for SOC SAL support
#

LOCALDIR = src/sal/appl

include ${SDK}/mk/Make.config

subdirs=${targetbase} editline

include ${SDK}/mk/Make.subdirs


lib = libsal_appl

include ${SDK}/mk/Make.lib

include ${SDK}/mk/Make.depend



